Repository WildCodeSchool/2023-03-JS-TLSE-P3-Innovin, pull requests merged in 2023-06, with the labels that each got.

#2 Grape variety
  backend/.env.sample
  backend/database.sql
  backend/src/controllers/GrapeVarietyControllers.js
  backend/src/models/GrapeVarietyManager.js
  backend/src/models/index.js
  backend/src/router.js
  package-lock.json
  package.json
Labels: Reviewed

#4 S03 us02 authentification
  backend/database.sql
  backend/src/auth.js
  backend/src/controllers/GrapeVarietyControllers.js
  backend/src/controllers/UserControllers.js
  backend/src/models/GrapeVarietyManager.js
  backend/src/models/UserManager.js
  backend/src/router.js
Labels: Changes requested, Corrections done

#9 S03 us6 wine region
  backend/src/controllers/WineRegionControllers.js
  backend/src/models/WineRegionManager.js
  backend/src/models/index.js
  backend/src/router.js
Labels: Reviewed, Corrections done

#10 S04 us04 appellation
  backend/src/controllers/AppellationControllers.js
  backend/src/models/AppellationManager.js
  backend/src/models/index.js
  backend/src/router.js
Labels: Conflicts

#11 S04_US03_existing_wine
  backend/src/controllers/ExistingWineControllers.js
  backend/src/models/ExistingWineManager.js
  backend/src/models/index.js
  backend/src/router.js
Labels: Reviewed

#18 S04 us03 existing wine
  backend/database.sql
  backend/src/controllers/ExistingWineControllers.js
  backend/src/models/ExistingWineManager.js
  backend/src/router.js
Labels: Reviewed

#19 S03 us29 new wine
  backend/database.sql
  backend/src/controllers/NewWineControllers.js
  backend/src/models/NewWineManager.js
  backend/src/models/index.js
  backend/src/router.js
Labels: Reviewed

#21 S04 us10 step0 presentation
  backend/database.sql
  backend/src/models/index.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/pages/TastingPresentation.jsx
  frontend/src/pages/TastingPresentation/TastingContext.jsx
  frontend/src/pages/TastingPresentation/TastingPresentation.css
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
Labels: Reviewed

#23 S04 us12 step2 eye
  frontend/index.html
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/Utils.js
  frontend/src/assets/Gold_Blotches/Watercolor_Blotch_1.png
  frontend/src/assets/Icons/Drop_Icon.svg
  frontend/src/assets/Icons/Hearth_Icon.svg
  frontend/src/assets/Icons/Intensity_Icon.svg
  frontend/src/assets/Icons/Mouth_Icon.svg
  frontend/src/assets/Icons/Nose_Icon.svg
  frontend/src/assets/Icons/Shiny_Icon_2.svg
  frontend/src/assets/Icons/Transparency_Icon.svg
  frontend/src/assets/Red_Wine_Colors/Cerise.png
  frontend/src/assets/Red_Wine_Colors/Framboise.png
  frontend/src/assets/Red_Wine_Colors/Grenat.png
  frontend/src/assets/Red_Wine_Colors/Pourpre.png
  frontend/src/assets/Red_Wine_Colors/Rouge_Noir.png
  frontend/src/assets/Red_Wine_Colors/Rubis.png
  frontend/src/assets/Red_Wine_Colors/Tuilé.png
  frontend/src/assets/Red_Wine_Colors/Violet.png
  frontend/src/components/Checkboxes/Checkboxes.css
  frontend/src/components/Checkboxes/Checkboxes.jsx
  frontend/src/components/StepsHeader/StepButton.jsx
  frontend/src/components/StepsHeader/StepsHeader.css
  frontend/src/components/StepsHeader/StepsHeader.jsx
  frontend/src/components/TastingHeaderTitle.css
  frontend/src/components/TastingHeaderTitle.jsx
  frontend/src/contexts/TastingNoteContext.jsx
  frontend/src/pages/Login/Login.css
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
  frontend/src/pages/VisualStage/VisualStage1.css
  frontend/src/pages/VisualStage/VisualStage1.jsx
  frontend/src/pages/VisualStage/VisualStage2.css
  frontend/src/pages/VisualStage/VisualStage2.jsx
Labels: Reviewed, Corrections done

#24 Fix défaut suite à PR sélection_competition
  backend/database.sql
  backend/src/router.js
Labels: Reviewed

#25 Fix defaults
  backend/database.sql
Labels: Reviewed

#26 Get data by theme
  backend/database.sql
  backend/src/controllers/TastingSheetsDatasControllers.js
  backend/src/models/OlfactiveManager.js
  backend/src/models/TasteManager.js
  backend/src/models/TastingAromasManager.js
  backend/src/models/VisualManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/components/StepsHeader/StepsHeader.jsx
  frontend/src/contexts/TastingContext.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/TastingPresentation/TastingContext.jsx
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
  frontend/src/pages/VisualStage/VisualStage1.jsx
  frontend/src/pages/VisualStage/VisualStage2.jsx
Labels: Reviewed

#27 S05 us01 workshop has existingwine
  backend/src/controllers/WorkshopHasExistingWineControllers.js
  backend/src/models/WorkshopHasExistingWineManager.js
  backend/src/models/index.js
  backend/src/router.js
Labels: Corrections done
