Repository WildCodeSchool/2023-03-JS-TLSE-P3-Innovin, pull requests merged in 2023-07, with the labels that each got.

#28 S05 us08 map
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/wine.geojson.js
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/pages/WinesMap/WinesMap.css
  frontend/src/pages/WinesMap/WinesMap.jsx
  package-lock.json
  package.json
Labels: Reviewed

#30 S05_US03_Registration_branche_complète
  backend/database.sql
  frontend/src/App.jsx
  frontend/src/assets/Linetxtregistration.svg
  frontend/src/components/CommentInput.jsx
  frontend/src/pages/Registration/Registration.css
  frontend/src/pages/Registration/Registration.jsx
  package-lock.json
Labels: Reviewed

#32 S05 us10 welcome
  frontend/src/assets/Icons/Glass_Wine_Icon3.svg
  frontend/src/assets/Icons/Up_Arrow.png
  frontend/src/assets/Icons/glass-wine-icon3.svg
  frontend/src/assets/Icons/mix-icon.svg
  frontend/src/assets/Icons/star-1.svg
  frontend/src/assets/Wine_Img/Creation_Header.png
  frontend/src/assets/Wine_Img/Frame123.png
  frontend/src/assets/Wine_Img/Illustration_Creation.png
  frontend/src/assets/line-11.svg
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/HomeTasting/HomeTasting.css
  frontend/src/pages/HomeTasting/HomeTasting.jsx
  frontend/src/pages/Registration/Registration.css
  frontend/src/pages/TastingPresentation/TastingPresentation.css
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
  frontend/src/pages/WinesMap/WinesMap.css
Labels: Reviewed

#34 S04 us13 step3 nose
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/Utils.js
  frontend/src/assets/Icons/Complexity_Icon.svg
  frontend/src/components/Aromas/Aromas.css
  frontend/src/components/Aromas/Aromas.jsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/pages/HomeTasting/HomeTasting.css
  frontend/src/pages/OlfactoryStage/OlfactoryStage.css
  frontend/src/pages/OlfactoryStage/OlfactoryStage.jsx
  frontend/src/pages/TastingPresentation/TastingPresentation.css
Labels: Corrections done

#35 Update HomeTasting.css
  backend/src/router.js
  frontend/src/pages/HomeTasting/HomeTasting.css
Labels: Reviewed

#38 S05 us13 admin sidebar
  backend/database.sql
  backend/src/auth.js
  backend/src/controllers/WorkshopControllers.js
  backend/src/models/WorkshopManager.js
  backend/src/router.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/Line.svg
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.css
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.jsx
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.scss
  frontend/src/components/ButtonPrimary.jsx
  frontend/src/contexts/AdminContext.jsx
  frontend/src/contexts/AuthContext.jsx
  frontend/src/pages/Admin/AdminHome/AdminHome.jsx
  frontend/src/pages/Admin/WorkshopsManagement/WorshopsManagement.jsx
  frontend/src/pages/Login/Login.css
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Login/Login.scss
  frontend/src/pages/Registration/Registration.css
  frontend/src/pages/TasteAdvice/TasteAdvice.jsx
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
  package-lock.json
  package.json
Labels: Reviewed

#39 S06 us01 step5 taste
  backend/src/controllers/TastingSheetsDatasControllers.js
  frontend/src/App.jsx
  frontend/src/assets/Icons/Time_Icon.svg
  frontend/src/components/Aromas/Aromas.css
  frontend/src/contexts/TastingContext.jsx
  frontend/src/contexts/TastingNoteContext.jsx
  frontend/src/pages/TasteStage1/TasteStage1.jsx
  frontend/src/pages/TasteStage1/TasteStage1.scss
  frontend/src/pages/TasteStage2/TasteStage2.css
  frontend/src/pages/TasteStage2/TasteStage2.jsx
  frontend/src/pages/TasteStage2/TasteStage2.scss
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
Labels: Reviewed

#41 S06 us04 creation workshop
  backend/database.sql
  backend/src/controllers/NewWineControllers.js
  backend/src/controllers/TastingNoteControllers.js
  backend/src/models/NewWineManager.js
  backend/src/models/TastingNoteManager.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/components/Sliders/Sliders.jsx
  frontend/src/components/Sliders/Sliders.scss
  frontend/src/components/TasteStage1Sliders/TasteStage1Sliders.jsx
  frontend/src/components/TasteStage1Sliders/TasteStage1Sliders.scss
  frontend/src/pages/CreationWorkshop/CreationWorkshop.css
  frontend/src/pages/CreationWorkshop/CreationWorkshop.jsx
  frontend/src/pages/CreationWorkshop/CreationWorkshop.scss
  frontend/src/pages/HomeTasting/HomeTasting.css
Labels: Reviewed

#42 S06 us07 workshops management
  backend/database.sql
  backend/src/controllers/WorkshopControllers.js
  backend/src/models/WorkshopManager.js
  frontend/package-lock.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.jsx
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.scss
  frontend/src/components/ButtonPrimary.jsx
  frontend/src/components/Dropdown/Dropdown.jsx
  frontend/src/components/Dropdown/Dropdown.scss
  frontend/src/components/Input.jsx
  frontend/src/components/SearchBar/SearchBar.jsx
  frontend/src/components/SearchBar/SearchBar.scss
  frontend/src/contexts/AdminContext.jsx
  frontend/src/pages/Admin/WorkshopModification/WorkshopModification.css
  frontend/src/pages/Admin/WorkshopModification/WorkshopModification.jsx
  frontend/src/pages/Admin/WorkshopModification/WorkshopModification.scss
  frontend/src/pages/Admin/WorkshopsManagement/WorkshopsManagement.css
  frontend/src/pages/Admin/WorkshopsManagement/WorkshopsManagement.scss
  frontend/src/pages/Admin/WorkshopsManagement/WorshopsManagement.jsx
  frontend/src/pages/Login/Login.scss
  frontend/src/pages/TasteAdvice/TasteAdvice.jsx
Labels: Reviewed

#43 Dev to main 13/07
  backend/database.sql
  backend/src/auth.js
  backend/src/controllers/NewWineControllers.js
  backend/src/controllers/TastingNoteControllers.js
  backend/src/controllers/TastingSheetsDatasControllers.js
  backend/src/controllers/WorkshopControllers.js
  backend/src/models/NewWineManager.js
  backend/src/models/TastingNoteManager.js
  backend/src/models/WorkshopManager.js
  backend/src/router.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/Icons/Time_Icon.svg
  frontend/src/assets/Line.svg
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.css
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.jsx
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.scss
  frontend/src/components/Aromas/Aromas.css
  frontend/src/components/ButtonPrimary.jsx
  frontend/src/components/Dropdown/Dropdown.jsx
  frontend/src/components/Dropdown/Dropdown.scss
  frontend/src/components/Input.jsx
  frontend/src/components/SearchBar/SearchBar.jsx
  frontend/src/components/SearchBar/SearchBar.scss
  frontend/src/components/Sliders/Sliders.jsx
  frontend/src/components/Sliders/Sliders.scss
  frontend/src/components/TasteStage1Sliders/TasteStage1Sliders.jsx
  frontend/src/components/TasteStage1Sliders/TasteStage1Sliders.scss
  frontend/src/contexts/AdminContext.jsx
  frontend/src/contexts/AuthContext.jsx
  frontend/src/contexts/TastingContext.jsx
  frontend/src/contexts/TastingNoteContext.jsx
  frontend/src/pages/Admin/AdminHome/AdminHome.jsx
  frontend/src/pages/Admin/WorkshopModification/WorkshopModification.css
  frontend/src/pages/Admin/WorkshopModification/WorkshopModification.jsx
  frontend/src/pages/Admin/WorkshopModification/WorkshopModification.scss
  frontend/src/pages/Admin/WorkshopsManagement/WorkshopsManagement.css
  frontend/src/pages/Admin/WorkshopsManagement/WorkshopsManagement.scss
  frontend/src/pages/Admin/WorkshopsManagement/WorshopsManagement.jsx
  frontend/src/pages/CreationWorkshop/CreationWorkshop.css
  frontend/src/pages/CreationWorkshop/CreationWorkshop.jsx
  frontend/src/pages/CreationWorkshop/CreationWorkshop.scss
  frontend/src/pages/HomeTasting/HomeTasting.css
  frontend/src/pages/Login/Login.css
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Login/Login.scss
  frontend/src/pages/Registration/Registration.css
  frontend/src/pages/TasteAdvice/TasteAdvice.jsx
  frontend/src/pages/TasteStage1/TasteStage1.jsx
  frontend/src/pages/TasteStage1/TasteStage1.scss
  frontend/src/pages/TasteStage2/TasteStage2.css
  frontend/src/pages/TasteStage2/TasteStage2.jsx
  frontend/src/pages/TasteStage2/TasteStage2.scss
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
  frontend/src/pages/VisualStage/VisualStage1.jsx
  package-lock.json
  package.json
Labels: Reviewed

#49 S06 us04 creation workshop
  backend/src/controllers/ExistingWineControllers.js
  backend/src/controllers/NewWineControllers.js
  backend/src/models/ExistingWineManager.js
  backend/src/models/NewWineManager.js
  backend/src/models/SelectedWineManager.js
  backend/src/models/TastingNoteManager.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/Icons/Grapes_Icon.svg
  frontend/src/components/Sliders/Sliders.jsx
  frontend/src/components/Sliders/Sliders.scss
  frontend/src/contexts/CreationWorkshopContext.jsx
  frontend/src/pages/BlendedWine/BlendedWine.jsx
  frontend/src/pages/BlendedWine/BlendedWine.scss
  frontend/src/pages/CreationWorkshop/CreationWorkshop.jsx
  package-lock.json
Labels: Reviewed, Corrections done

#51 S06 us02 wine tasted
  backend/database.sql
  backend/src/router.js
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/Utils.js
  frontend/src/assets/Icons/Star_Default_Icon.svg
  frontend/src/assets/Icons/Tasting_Note_Icon.svg
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/contexts/TastingNoteContext.jsx
  frontend/src/pages/CreationWorkshop/CreationWorkshop.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/OlfactoryStage/OlfactoryStage.jsx
  frontend/src/pages/Revelation/CardRevelation.jsx
  frontend/src/pages/Revelation/Revelation.css
  frontend/src/pages/Revelation/Revelation.jsx
  frontend/src/pages/Revelation/cardrevelation.css
  frontend/src/pages/WinesTasted/Card.jsx
  frontend/src/pages/WinesTasted/WinesTasted.css
  frontend/src/pages/WinesTasted/WinesTasted.jsx
  frontend/src/pages/WinesTasted/card.css
  package-lock.json
Labels: Reviewed

#53 fix et correctifs
  frontend/src/components/Sliders/Sliders.jsx
  frontend/src/contexts/CreationWorkshopContext.jsx
  frontend/src/pages/CreationWorkshop/CreationWorkshop.jsx
  frontend/src/pages/Revelation/Revelation.jsx
  frontend/src/pages/WinesTasted/WinesTasted.jsx
  package-lock.json
Labels: Reviewed, Corrections done

#54 Glossary
  frontend/src/App.jsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/pages/Glossary/Glossary.css
  frontend/src/pages/Glossary/Glossary.jsx
  frontend/src/pages/Glossary/lexique-vin.js
  frontend/src/pages/WinesTasted/WinesTasted.css
Labels: Reviewed

#55 S06 us08 wines manager
  backend/database.sql
  backend/src/controllers/ExistingWineControllers.js
  backend/src/controllers/WineryControllers.js
  backend/src/models/ExistingWineManager.js
  backend/src/models/WineryManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Admin_Dashboard/Admin_Dashboard.jsx
  frontend/src/components/ButtonPrimary.jsx
  frontend/src/components/Dropdown/Dropdown.scss
  frontend/src/components/ModalValidation/ModalValidation.jsx
  frontend/src/components/ModalValidation/ModalValidation.scss
  frontend/src/components/SearchOrAdd/SearchOrAdd.jsx
  frontend/src/components/SearchOrAdd/SearchOrAdd.scss
  frontend/src/pages/Admin/UsersManagement/UsersManagement.jsx
  frontend/src/pages/Admin/UsersManagement/UsersManagement.scss
  frontend/src/pages/Admin/UsersModification/UsersModification.jsx
  frontend/src/pages/Admin/UsersModification/UsersModification.scss
  frontend/src/pages/Admin/WinesCreation/WinesCreation.jsx
  frontend/src/pages/Admin/WinesCreation/WinesCreation.scss
  frontend/src/pages/Admin/WinesSheetsManagement/WinesSheetsManagement.css
  frontend/src/pages/Admin/WinesSheetsManagement/WinesSheetsManagement.jsx
  frontend/src/pages/Admin/WinesSheetsManagement/WinesSheetsManagement.scss
  frontend/src/pages/Admin/WorkshopCreation/WorkshopCreation.scss
  frontend/src/pages/Admin/WorkshopModification/WorkshopModification.scss
  frontend/src/pages/Admin/WorkshopsManagement/WorkshopsManagement.scss
  frontend/src/pages/Admin/WorkshopsManagement/WorshopsManagement.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/WinesMap/WinesMap.css
  frontend/src/pages/WinesTasted/Card.jsx
  frontend/src/pages/WinesTasted/WinesTasted.css
  frontend/src/pages/WinesTasted/card.css
Labels: Reviewed

#57 Fix css1
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Aromas/Aromas.css
  frontend/src/components/ScrolltoTop/Scroll.jsx
  frontend/src/pages/Glossary/Glossary.css
  frontend/src/pages/Glossary/Glossary.jsx
  frontend/src/pages/Glossary/Glossary.scss
  frontend/src/pages/Glossary/lexique-vin.js
  frontend/src/pages/OlfactoryStage/OlfactoryStage.css
  frontend/src/pages/OlfactoryStage/OlfactoryStage.jsx
  frontend/src/pages/OlfactoryStage/OlfactoryStage.scss
  frontend/src/pages/Revelation/Revelation.css
  frontend/src/pages/Revelation/cardrevelation.css
  frontend/src/pages/TastingPresentation/TastingPresentation.css
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
  frontend/src/pages/TastingPresentation/TastingPresentation.scss
  frontend/src/pages/WinesMap/WinesMap.css
  frontend/src/pages/WinesMap/WinesMap.jsx
  frontend/src/pages/WinesMap/WinesMap.scss
  frontend/src/pages/WinesTasted/Card.jsx
  frontend/src/pages/WinesTasted/WinesTasted.css
  frontend/src/pages/WinesTasted/WinesTasted.jsx
  frontend/src/pages/WinesTasted/WinesTasted.scss
  frontend/src/pages/WinesTasted/card.css
  frontend/src/pages/WinesTasted/card.scss
Labels: Reviewed

#59 S08 fix css
  frontend/src/App.css
  frontend/src/assets/Frame_123.svg
  frontend/src/assets/Line_10.svg
  frontend/src/assets/Line_9.svg
  frontend/src/components/Aromas/Aromas.css
  frontend/src/components/Aromas/Aromas.jsx
  frontend/src/components/Aromas/Aromas.scss
  frontend/src/components/ButtonPrimary.jsx
  frontend/src/components/Checkboxes/Checkboxes.css
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/Footer.scss
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Navbar/Navbar.scss
  frontend/src/components/Sliders/Sliders.scss
  frontend/src/components/StepsHeader/StepButton.jsx
  frontend/src/components/StepsHeader/StepsHeader.css
  frontend/src/components/StepsHeader/StepsHeader.jsx
  frontend/src/components/StepsHeader/StepsHeader.scss
  frontend/src/components/TasteStage1Sliders/TasteStage1Sliders.jsx
  frontend/src/components/TasteStage1Sliders/TasteStage1Sliders.scss
  frontend/src/components/TastingHeaderTitle.css
  frontend/src/components/TastingHeaderTitle.jsx
  frontend/src/components/TastingHeaderTitle.scss
  frontend/src/pages/CreationWorkshop/CreationWorkshop.scss
  frontend/src/pages/HomeTasting/HomeTasting.css
  frontend/src/pages/HomeTasting/HomeTasting.jsx
  frontend/src/pages/HomeTasting/HomeTasting.scss
  frontend/src/pages/OlfactoryStage/OlfactoryStage.jsx
  frontend/src/pages/OlfactoryStage/OlfactoryStage.scss
  frontend/src/pages/TasteAdvice/TasteAdvice.jsx
  frontend/src/pages/TasteAdvice/TasteAdvice.scss
  frontend/src/pages/TasteStage1/TasteStage1.jsx
  frontend/src/pages/TasteStage1/TasteStage1.scss
  frontend/src/pages/TasteStage2/TasteStage2.jsx
  frontend/src/pages/TasteStage2/TasteStage2.scss
  frontend/src/pages/VisualStage/VisualStage1.css
  frontend/src/pages/VisualStage/VisualStage1.jsx
  frontend/src/pages/VisualStage/VisualStage1.scss
  frontend/src/pages/VisualStage/VisualStage2.css
  frontend/src/pages/VisualStage/VisualStage2.jsx
  frontend/src/pages/VisualStage/VisualStage2.scss
Labels: Reviewed

#60 S08 us03 blended wine and ending
  backend/database.sql
  backend/src/controllers/NewWineControllers.js
  backend/src/models/NewWineManager.js
  backend/src/router.js
  frontend/src/contexts/CreationWorkshopContext.jsx
  frontend/src/contexts/TastingNoteContext.jsx
  frontend/src/pages/BlendedWine/BlendedWine.jsx
  frontend/src/pages/CreationWorkshop/CreationWorkshop.jsx
  frontend/src/pages/Revelation/Revelation.jsx
  frontend/src/pages/WinesTasted/WinesTasted.jsx
Labels: Reviewed

#62 S08 fix css again
  frontend/src/components/TastingHeaderTitle.jsx
  frontend/src/components/TastingHeaderTitle.scss
Labels: Reviewed

#64 Remplacement URL, suppression pages vides et inutiles
  frontend/src/components/Hue/Hue.css
  frontend/src/components/Hue/Hue.jsx
  frontend/src/components/RegisteredAttendees/RegisteredAttendees.css
  frontend/src/components/RegisteredAttendees/RegisteredAttendees.jsx
  frontend/src/components/WeeklyWorkshops/WeeklyWorkshops.css
  frontend/src/components/WeeklyWorkshops/WeeklyWorkshops.jsx
  frontend/src/pages/About/About.css
  frontend/src/pages/About/About.jsx
  frontend/src/pages/Admin/CompetitionSelection/CompetitionSelection.css
  frontend/src/pages/Admin/CompetitionSelection/CompetitionSelection.jsx
  frontend/src/pages/Admin/TastingSheetsManagement/TastingSheetsManagement.css
  frontend/src/pages/Admin/TastingSheetsManagement/TastingSheetsManagement.jsx
  frontend/src/pages/Admin/TastingSheetsModification/TastingSheetsModification.css
  frontend/src/pages/Admin/TastingSheetsModification/TastingSheetsModification.jsx
  frontend/src/pages/Admin/WinesSheetsModification/WinesSheetsModification.css
  frontend/src/pages/Admin/WinesSheetsModification/WinesSheetsModification.jsx
  frontend/src/pages/Contact/Contact.css
  frontend/src/pages/Contact/Contact.jsx
  frontend/src/pages/Revelation/Revelation.jsx
  frontend/src/pages/TastingPresentation/TastingPresentation.jsx
  frontend/src/pages/WineReviews/WineReviews.css
  frontend/src/pages/WineReviews/WineReviews.jsx
  frontend/src/pages/WinesTasted/WinesTasted.jsx
Labels: Reviewed

#65 S08 fix css
  frontend/src/components/TasteStage1Sliders/TasteStage1Sliders.jsx
  frontend/src/pages/BlendedWine/BlendedWine.jsx
  frontend/src/pages/BlendedWine/BlendedWine.scss
  frontend/src/pages/CreationWorkshop/CreationWorkshop.jsx
  frontend/src/pages/CreationWorkshop/CreationWorkshop.scss
  frontend/src/pages/HomeTasting/HomeTasting.scss
  frontend/src/pages/OlfactoryStage/OlfactoryStage.scss
  frontend/src/pages/Registration/Registration.css
  frontend/src/pages/Registration/Registration.jsx
  frontend/src/pages/Registration/Registration.scss
  frontend/src/pages/Revelation/CardRevelation.jsx
  frontend/src/pages/Revelation/Revelation.jsx
  frontend/src/pages/Revelation/Revelation.scss
  frontend/src/pages/Revelation/cardrevelation.scss
  frontend/src/pages/TasteAdvice/TasteAdvice.scss
  frontend/src/pages/TasteStage1/TasteStage1.scss
  frontend/src/pages/TasteStage2/TasteStage2.scss
  frontend/src/pages/VisualStage/VisualStage1.jsx
  frontend/src/pages/VisualStage/VisualStage1.scss
  frontend/src/pages/VisualStage/VisualStage2.scss
  frontend/src/pages/WinesMap/WinesMap.scss
  frontend/src/pages/WinesTasted/Card.jsx
  frontend/src/pages/WinesTasted/WinesTasted.scss
  frontend/src/pages/WorkshopEnding/WorkshopEnding.jsx
  frontend/src/pages/WorkshopEnding/WorkshopEnding.scss
Labels: Reviewed

#67 hot CSS fix
  frontend/src/pages/Registration/Registration.jsx
  frontend/src/pages/Registration/Registration.scss
  frontend/src/pages/TasteStage2/TasteStage2.scss
Labels: Reviewed

#68 Ultimate final
  frontend/src/pages/Registration/Registration.jsx
  frontend/src/pages/Registration/Registration.scss
  frontend/src/pages/TasteStage2/TasteStage2.scss
Labels: Reviewed
